Refactor - Policy page
Nestsoft-Team/DunJi-FrontEnd pull request #97
Opened 2022-12-13 13:33 UTC by sumi-0011

2022-12-14 01:38 UTC, sumi-0011 commented on client/login/oauth_kakao/index.tsx
> +  }, [dispatch]);
useEffect에 들어가 있는 로직은 위에 함수로 빼서 무슨 일을 하고있는 함수있지 명확히

2022-12-14 01:38 UTC, sumi-0011 commented on client/register/form-item.tsx
> +  );
중복 컴포넌트 분리

2022-12-14 01:38 UTC, sumi-0011 commented on client/register/policy.tsx
> +        ))}
중복 컴포넌트분리

2022-12-14 01:38 UTC, sumi-0011 commented on client/register/policy.tsx
> +  const { checks, checkAll, handleCheck, handleAllCheck } = useChecks(4);
useChecks 훅 추가 후에 정리 필요

2022-12-14 01:38 UTC, sumi-0011 commented on hooks/useChecks.ts
> +  const [checkAll, setCheckAll] = useState(false);
useToggle과 같은 훅도 만들면 좋을거같아여

2022-12-14 01:38 UTC, sumi-0011 commented on pages/register/policy.tsx
> +  return { props: {} };
서버사이드 전처리작업, 페이지 분리

2022-12-15 04:05 UTC, Dragonite-Lee commented on pages/register/policy.tsx
> +export async function getServerSideProps() {
pages에서 저렇게 사용하고 App wrapper로 감싸주고 store에서 Hydrate이용하면 될 것 같아요!

2022-12-17 07:20 UTC, junbox98221 requested changes

2022-12-17 07:20 UTC, junbox98221 commented on client/register/form-item.tsx
> +  );
```ts
interface propsType extends InputHTMLAttributes<HTMLInputElement> {
  label: string;
}

export function Input({ label, ...props }: propsType) {
  return (
    <>
      <label className="text-lg mb-2 mt-4 font-bold">{label}</label>
      <input
        className="outline-0 border-blur border h-12 pl-4 focus:border-yellow"
        {...props}
      />
    </>
  );
}
```

확장성? 고려해서 input props를 위처럼 받으면 좋을 것 같아요

2022-12-17 07:20 UTC, junbox98221 commented on client/register/policy-item.tsx
> +  handleCheck: () => void;
알파벳 순서 정렬

2022-12-17 07:20 UTC, junbox98221 commented on client/register/policy-item.tsx
> +  handleCheck,
여기도 정렬이요!

2022-12-17 07:21 UTC, junbox98221 approved these changes

2022-12-18 10:21 UTC, junbox98221 commented
컴포넌트 네이밍 Upper Camel Case 로 하는게 어떨까요

2022-12-18 14:33 UTC, sumi-0011 commented on client/register/policy-item.tsx
> +  handleCheck: () => void;
변수, 함수, 가변 인자 순서로 같은 것끼린 알파벳 순서로.

2022-12-18 14:34 UTC, merged